name: Build DSC archives
permissions:
  contents: read

on:
  workflow_dispatch:
  push: 
    branches: [main]

jobs:
  # TODO: Consider caching deps: https://docs.github.com/en/actions/tutorials/build-and-test-code/powershell#caching-dependencies
  install-dependencies:
    name: Install dependencies
    runs-on: windows-latest
    env:
      dsc_folder: "${{ github.workspace }}/sharepoint-adfs-full"
    steps:
      - uses: actions/checkout@v6
      - name: Setup PowerShell module cache
        if: false
        id: cacher
        uses: actions/cache@v5
        with:
          path: "~/.local/share/powershell/Modules"
          key: ${{ runner.os }}-mandatory-modules
      - name: Install mandatory modules
        #if: steps.cacher.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Az.Compute #, PSDesiredStateConfiguration

      - name: Install dsc modules
        shell: powershell
        env:
          scriptsFolder: "${{ github.workspace }}/scripts"
        run: |
          Write-Host "Get DSC files in folder '${{ env.dsc_folder }}'"
          $dscFilesPath = Get-ChildItem "${{ env.dsc_folder }}" -File -Filter "dsc-*.ps1"
          foreach ($dscFilePath in $dscFilesPath) {
              $dscMissingModules = ${{ env.scriptsFolder }}/Get-MissingDscModules.ps1 -dscFilePath "$($dscFilePath.FullName)"
              Write-Host "Found $($dscMissingModules.Count) missing DSC module(s) for '$dscFilePath'."
              foreach ($dscMissingModule in $dscMissingModules) {
                Write-Host "Installing module '$($dscMissingModule.Name)' version '$($dscMissingModule.Version)'..."
                Install-Module -Name $dscMissingModule.Name -RequiredVersion $dscMissingModule.Version -Scope AllUsers
              }
          }

      - name: Replace customized modules
        shell: powershell
        env:
          customModulesFolder: "${{ github.workspace }}/customized-modules"
        run: |
          $modulesLocation = "$($Env:ProgramFiles)\WindowsPowerShell\Modules"
          $customModulesPath = Get-ChildItem "${{ env.customModulesFolder }}" -Directory
          foreach ($customModulePath in $customModulesPath) {
            Write-Host "Replacing module '$($customModulePath.BaseName)' with its customized version..."
            Move-Item -Force -Recurse -Path $customModulePath -Destination $modulesLocation
          }

      - name: Build DSC archives
        shell: powershell
        env:
          scriptsFolder: "${{ github.workspace }}/scripts"
        run: |
          $dscFilesPath = Get-ChildItem "${{ env.dsc_folder }}" -File -Filter "dsc-*.ps1"
          foreach ($dscFilePath in $dscFilesPath) {
              Write-Host "Creating DSC archive for '$($dscFilePath.BaseName)'."
              ${{ env.scriptsFolder }}/New-DscArchive.ps1 -vmName "$($dscFilePath.BaseName)" -dscFolderPath "${{ env.dsc_folder }}"
          }

      - uses: actions/upload-artifact@v7
        with:
          name: dsc-archives
          path: ${{ env.dsc_folder }}/*.zip
