name: Build DSC archives
permissions:
  contents: read

on:
  workflow_dispatch:
  push: 
    branches: main

jobs:
  # TODO: Consider caching deps: https://docs.github.com/en/actions/tutorials/build-and-test-code/powershell#caching-dependencies
  install-dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    env:
      dsc_folder: "${{ github.workspace }}/sharepoint-adfs-full"
    steps:
      - uses: actions/checkout@v6
      - name: Setup PowerShell module cache
        id: cacher
        uses: actions/cache@v5
        with:
          path: "~/.local/share/powershell/Modules"
          key: ${{ runner.os }}-AzCompute
      - name: Install mandatory modules
        if: steps.cacher.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Az.Compute

      - name: Install dsc modules
        shell: pwsh
        env:
          scriptsFolder: "${{ github.workspace }}/scripts"
        run: |
          Write-Host "Get DSC files in folder '${{ env.dsc_folder }}'"
          $dscFilesPath = Get-ChildItem ${{ env.dsc_folder }} -File -Filter "dsc-*.ps1"
          foreach ($dscFilePath in $dscFilesPath) {
              $dscModules = ${{ env.scriptsFolder }}/Get-DscModules.ps1 -dscFilePath "$dscFilePath"
              Write-Host "Found $($dscModules.Count) DSC modules for '$dscFilePath':"
              foreach ($module in $dscModules.GetEnumerator()) {
                Write-Host "Requires module '$($module.Key)' version '$($module.Value)'"
              }
          }
